### ISSUE TITLE
something won't work...

### ISSUE THREAD

**Issue by EzzyKillS** [NotJINXZ/duolingo-emailspammer#1]
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ezzykills/Desktop/duolingo-emailspammer/spammer.py", line 23, in profile
    account = self.register()
  File "/home/ezzykills/Desktop/duolingo-emailspammer/spammer.py", line 20, in register
    return response.cookies['jwt_token'], response.json()['id']
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='jwt_token', domain=None, path=None"

**Comment by RoyaleOne** [comment]
same here

**Comment by haze-1337** [comment]
forget it, this guy skidded my repository word for word ; duolingo patched this today

**Comment by EzzyKillS** [comment]
> forget it, this guy skidded my repository word for word ; duolingo patched this today

so there is in solution for now? rip
